services:
  matching:
    environment:
      HANWOO_DEVICE: auto
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

  anomaly:
    environment:
      HANWOO_DEVICE: auto
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
  
  dinomaly:
    environment:
      HANWOO_DEVICE: auto
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
